ARG  PYTHON_VERSION=3.13
FROM python:${PYTHON_VERSION}-alpine AS base

RUN mkdir -p /usr/src/app
RUN mkdir -p /output
WORKDIR /usr/src/app

RUN pip install --no-cache-dir setuptools

COPY telegramer /usr/src/app/telegramer
COPY setup.py /usr/src/app/setup.py
COPY LICENSE /usr/src/app/LICENSE
COPY build_egg.sh /usr/src/app/build_egg.sh

RUN sh build_egg.sh
